function [ axes1 ] = demo_tomo_surf(zdata1, z_level)
%CREATEFIGURE(ZDATA1)
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 16-Oct-2016 09:34:54

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create surf
zdata = squeeze(zdata1);
s = size(zdata);
%[x,y] = meshgrid(1:s(1), 1:s(2));
z(1:s(1), 1:s(2)) = z_level;
surf(z, zdata,'Parent',axes1,'LineStyle',':',...
    'EdgeColor',[0.678431391716003 0.921568632125854 1]);

% Create xlabel
xlabel('x (mm)');

% Create ylabel
ylabel('y (mm)');

% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[0 7500]);
view(axes1,[-37.5 30]);
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',24,'FontWeight','bold');
