function search_entries_start_figure(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 16-Oct-2016 11:09:34

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(Y1,'LineWidth',3);

% Create xlabel
xlabel('t (arb. units, \Omega = 68MHz)');

% Create ylabel
ylabel('E_n');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[450 1000]);
ylim(axes1,[0 0.1]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',24,'FontWeight','bold','XGrid','on','YGrid','on');
