function bscanfigure(figure1, xdata1, ydata1, zdata1, p)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1)
%  XDATA1:  contour x
%  YDATA1:  contour y
%  ZDATA1:  contour z

%  Auto-generated by MATLAB on 16-Mar-2016 09:00:29

lims = p.lims;

% Create axes
axes1 = axes('Parent',figure1,'BoxStyle','full','Layer','top',...
    'CLim', lims);
box(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel('h, mm');

% Create xlabel
xlabel('l, mm');

% Create contour
contourf(xdata1,ydata1,zdata1,'LineStyle','none','LevelStep',(lims(2)-lims(1))/p.colorStep);
axis ij;
%contourf(xdata1,ydata1,zdata1,'LineStyle','none');


% Create colorbar
colorbar('peer',axes1,'Limits',lims);
%colorbar('peer',axes1);

