function demo_ust5m_signals(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 26-Feb-2016 07:15:37

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','FontWeight','bold',...
    'FontSize',24);
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 2041]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 1024]);
box(axes1,'on');
hold(axes1,'on');

% Create xlabel
xlabel('t (arb. units)');
ylabel('A (arb. units)');

% Create multiple lines using matrix input to plot
plot(YMatrix1','LineWidth',2);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontSize',16);

