function demo_surface(fit_obj)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 03-Apr-2016 09:05:14

% Create figure
figure;


%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 2.5]);

% Create zlabel
zlabel('h(mm)');

% Create ylabel
ylabel('y, (mm)');

% Create xlabel
xlabel('x, (mm)');

% Create surf
plot(fit_obj);

