function [ h ] =  demo_bolded(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 19-Jan-2016 09:21:44

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','FontWeight','bold',...
    'FontSize',24);
%% Uncomment the following line to preserve the X-limits of the axes
 %xlim(axes1,[0 2041]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1024]);
box(axes1,'on');
hold(axes1,'on');

% Create xlabel
xlabel('t (arb. units)');

% Create plot
h = plot(Y1,'LineWidth',3);
end

