function demo_signal_plot(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 07-Oct-2016 07:30:40

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth',2);

% Create xlabel
% xlabel('h (mm)');
xlabel('h (arb. units)');

% Create ylabel
ylabel('A (arb. units)');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[1 2041]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',24,'FontWeight','bold','XGrid','on','YGrid','on');
