function [files] = specimens_path(specimens, root, fileName)
%SPECIMENS_PATH Summary of this function goes here
%   Detailed explanation goes here

specimensS = size(specimens);
for lcSpecimen=1:specimensS(2)
    specimen = specimens(lcSpecimen);
    name = specimen.specimen;
    states = specimen.states;
    statesS = size(states);
    for lcS=1:statesS(2)
        state = states(lcS);
        files(lcSpecimen, lcS) = struct(...
            "fileName"...
            , strcat(...
                root...
                , "\\", name...
                , "\\", state...
                , "\\", fileName...
                )...
            , "label"...
            , strcat(...
                name...
                , "-", state...
                )...
            );
    end
end

end

